name: Detekt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v5

      - name: Setup Java SDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v5

      - name: Detekt
        run: ./gradlew detekt

      - name: Upload Detekt Release report to GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report.html
          path: build/reports/detekt/detekt.html